import {MARKETPLACE_POLICY,resolveSalePolicy} from './marketplace-policy.mjs';
const DEFAULT_RESERVE_DAYS=14;

export function resolveFeePolicy(env={},nowMs=Date.now()){
 const configured=Number(env.MARKETPLACE_FEE_BPS),basisPoints=Number.isInteger(configured)&&configured>=0&&configured<=10000?configured:MARKETPLACE_POLICY.standardFeeBasisPoints;
 const reserve=Number(env.CREATOR_PAYOUT_RESERVE_DAYS),reserveDays=Number.isInteger(reserve)&&reserve>=0&&reserve<=365?reserve:DEFAULT_RESERVE_DAYS;
 return{basisPoints,fixedOrderFeeCents:0,fixedLineFeeCents:0,reserveDays,effectiveAt:new Date(nowMs).toISOString(),developmentDefault:false};
}
export async function getEffectiveFeePolicy(database,env={},nowMs=Date.now()){try{const row=await database.prepare("SELECT * FROM marketplace_fee_policies WHERE effective_at<=? ORDER BY effective_at DESC,id DESC LIMIT 1").bind(new Date(nowMs).toISOString()).first();if(row)return{basisPoints:Number(row.percentage_basis_points),fixedOrderFeeCents:Number(row.fixed_order_fee_cents),fixedLineFeeCents:Number(row.fixed_line_fee_cents),reserveDays:resolveFeePolicy(env,nowMs).reserveDays,effectiveAt:row.effective_at,developmentDefault:false,policyId:Number(row.id)};}catch{}return resolveFeePolicy(env,nowMs);}
export async function recordFeePolicy(database,input){const bps=Number(input.basisPoints),line=Number(input.fixedLineFeeCents||0),order=Number(input.fixedOrderFeeCents||0),actor=String(input.operatorActor||''),now=String(input.effectiveAt||new Date().toISOString()),note=String(input.note||'').slice(0,1000);if(!Number.isInteger(bps)||bps<0||bps>10000||![line,order].every(value=>Number.isInteger(value)&&value>=0)||!actor)throw new Error('Fee policy is invalid.');await database.batch([database.prepare("INSERT INTO marketplace_fee_policies(percentage_basis_points,fixed_order_fee_cents,fixed_line_fee_cents,effective_at,created_by,note,created_at) VALUES(?,?,?,?,?,?,?)").bind(bps,order,line,now,actor,note,now),database.prepare("INSERT INTO creator_financial_audit(actor_type,actor_id,action,context_json,created_at) VALUES('operator',?,'fee_policy_recorded',?,?)").bind(actor,JSON.stringify({basisPoints:bps,fixedOrderFeeCents:order,fixedLineFeeCents:line,effectiveAt:now}),now)]);return{basisPoints:bps,effectiveAt:now};}

export async function creatorSaleStatements(database,order,policy,paidAt){
 let result,aligned=true;try{result=await database.prepare(`SELECT oi.*,COALESCE(cl.creator_id,cb.creator_id) creator_id,cl.id product_identity_id,COALESCE((SELECT corrected_timestamp FROM creator_first_publication_corrections c WHERE c.listing_id=cl.id ORDER BY c.id DESC LIMIT 1),cl.first_published_at) first_published_at FROM order_items oi LEFT JOIN creator_listings cl ON cl.source_product_slug=oi.product_slug OR cl.public_product_slug=oi.product_slug LEFT JOIN creator_bundles cb ON cb.public_bundle_slug=oi.product_slug AND cb.publication_state='published' WHERE oi.order_id=?`).bind(Number(order.id)).all();}catch{aligned=false;try{result=await database.prepare(`SELECT oi.*,COALESCE(cl.creator_id,cb.creator_id) creator_id FROM order_items oi LEFT JOIN creator_listings cl ON cl.source_product_slug=oi.product_slug OR cl.public_product_slug=oi.product_slug LEFT JOIN creator_bundles cb ON cb.public_bundle_slug=oi.product_slug AND cb.publication_state='published' WHERE oi.order_id=?`).bind(Number(order.id)).all();}catch{return[];}}
 const availableAt=new Date(Date.parse(paidAt)+policy.reserveDays*86400000).toISOString(),statements=[];
 for(const line of result.results||[]){if(!line.creator_id)continue;const applied=aligned?await resolveSalePolicy(database,{creatorId:line.creator_id,firstPublishedAt:line.first_published_at,nowMs:Date.parse(paidAt)}):{basisPoints:policy.basisPoints,reason:'legacy'},quantity=Number(line.quantity),gross=Number(line.line_total_cents),discount=Math.max(0,Number(line.list_price_cents)*quantity-gross),fee=Math.min(gross,Math.round(gross*applied.basisPoints/10000)+policy.fixedLineFeeCents),net=gross-fee,key=`sale:${order.id}:${line.id}`;
  statements.push(aligned?database.prepare(`INSERT OR IGNORE INTO creator_sale_snapshots(order_id,order_item_id,creator_id,product_slug,product_title,unit_list_price_cents,unit_price_paid_cents,quantity,discount_cents,gross_cents,fee_basis_points,fixed_fee_cents,marketplace_fee_cents,creator_net_cents,currency,sold_at,product_identity_id,policy_reason) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(Number(order.id),Number(line.id),line.creator_id,line.product_slug,line.product_title_snapshot,Number(line.list_price_cents),Number(line.effective_unit_price_cents),quantity,discount,gross,applied.basisPoints,policy.fixedLineFeeCents,fee,net,String(line.currency).toUpperCase(),paidAt,line.product_identity_id,applied.reason):database.prepare(`INSERT OR IGNORE INTO creator_sale_snapshots(order_id,order_item_id,creator_id,product_slug,product_title,unit_list_price_cents,unit_price_paid_cents,quantity,discount_cents,gross_cents,fee_basis_points,fixed_fee_cents,marketplace_fee_cents,creator_net_cents,currency,sold_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(Number(order.id),Number(line.id),line.creator_id,line.product_slug,line.product_title_snapshot,Number(line.list_price_cents),Number(line.effective_unit_price_cents),quantity,discount,gross,applied.basisPoints,policy.fixedLineFeeCents,fee,net,String(line.currency).toUpperCase(),paidAt));
  statements.push(database.prepare(`INSERT OR IGNORE INTO creator_earnings_ledger(creator_id,entry_type,amount_cents,currency,order_id,order_item_id,product_slug,available_at,payout_state,reason,idempotency_key,created_at) VALUES(?,'sale_earning',?,?,?,?,?,?,?,'Creator sale earning',?,?)`).bind(line.creator_id,net,String(line.currency).toUpperCase(),Number(order.id),Number(line.id),line.product_slug,availableAt,policy.reserveDays?'pending':'available',key,paidAt));
 }
 return statements;
}

export async function recordOrderReversal(database,{orderId,type="refund_reversal",amountCents=null,eventId,createdAt=new Date().toISOString()}){
 if(!["refund_reversal","chargeback_reversal"].includes(type)||!String(eventId||'').trim())throw new Error("Invalid reversal type or event ID.");if(await database.prepare("SELECT id FROM creator_reversal_snapshots WHERE provider_event_id=? LIMIT 1").bind(String(eventId)).first())return[];const sales=await rows(database.prepare("SELECT * FROM creator_sale_snapshots WHERE order_id=? ORDER BY id").bind(Number(orderId))),entries=[],statements=[];let remaining=Number.isInteger(amountCents)?amountCents:sales.reduce((sum,row)=>sum+Number(row.gross_cents),0);
 for(const sale of sales){if(remaining<=0)break;const prior=await database.prepare("SELECT COALESCE(SUM(gross_reversed_cents),0) gross FROM creator_reversal_snapshots WHERE order_item_id=?").bind(Number(sale.order_item_id)).first(),refundable=Math.max(0,Number(sale.gross_cents)-Number(prior?.gross||0)),reversedGross=Math.min(remaining,refundable);if(!reversedGross)continue;const reversedNet=Math.min(Number(sale.creator_net_cents),Math.round(Number(sale.creator_net_cents)*reversedGross/Number(sale.gross_cents||1))),key=`${type}:${eventId}:${sale.order_item_id}`;statements.push(database.prepare("INSERT INTO creator_reversal_snapshots(order_id,order_item_id,creator_id,reversal_type,gross_reversed_cents,creator_net_reversed_cents,currency,provider_event_id,created_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(Number(orderId),Number(sale.order_item_id),sale.creator_id,type,reversedGross,reversedNet,sale.currency,String(eventId),createdAt),database.prepare(`INSERT INTO creator_earnings_ledger(creator_id,entry_type,amount_cents,currency,order_id,order_item_id,product_slug,available_at,payout_state,reason,idempotency_key,created_at) VALUES(?,?,?,?,?,?,?,?,?,'Payment reversal',?,?)`).bind(sale.creator_id,type,-reversedNet,sale.currency,Number(orderId),Number(sale.order_item_id),sale.product_slug,createdAt,'available',key,createdAt));entries.push({creatorId:sale.creator_id,amountCents:-reversedNet});remaining-=reversedGross;}
 if(statements.length)await database.batch(statements);
 return entries;
}

export async function getCreatorFinance(database,creatorId,{from="",to="",nowMs=Date.now()}={}){const where=["creator_id=?"],bind=[creatorId],saleWhere=["creator_id=?"],saleBind=[creatorId];if(from){where.push("created_at>=?");bind.push(from);saleWhere.push("sold_at>=?");saleBind.push(from);}if(to){where.push("created_at<?");bind.push(to);saleWhere.push("sold_at<?");saleBind.push(to);}const entries=await rows(database.prepare(`SELECT id,entry_type,amount_cents,currency,order_id,product_slug,available_at,payout_state,reason,created_at FROM creator_earnings_ledger WHERE ${where.join(" AND ")} ORDER BY created_at DESC,id DESC`).bind(...bind)),sales=await rows(database.prepare(`SELECT product_slug,product_title,quantity,gross_cents,marketplace_fee_cents,creator_net_cents,currency,sold_at FROM creator_sale_snapshots WHERE ${saleWhere.join(" AND ")} ORDER BY sold_at,id`).bind(...saleBind)),result=summarize(entries,new Date(nowMs).toISOString());result.summary.grossSalesCents=sales.reduce((sum,row)=>sum+Number(row.gross_cents),0);result.summary.marketplaceFeesCents=sales.reduce((sum,row)=>sum+Number(row.marketplace_fee_cents),0);result.summary.unitsSold=sales.reduce((sum,row)=>sum+Number(row.quantity),0);result.sales=sales;return result;}
export async function getOperatorFinance(database,{nowMs=Date.now()}={}){const creators=await rows(database.prepare("SELECT id,slug,display_name,payout_profile_status,tax_document_required FROM marketplace_creators ORDER BY display_name")),balances=[];for(const creator of creators){const finance=await getCreatorFinance(database,creator.id,{nowMs}),last=await database.prepare("SELECT paid_at,amount_cents,reference FROM creator_payouts WHERE creator_id=? AND status='paid' ORDER BY paid_at DESC LIMIT 1").bind(creator.id).first();balances.push({...creator,...finance.summary,lastPayout:last||null});}const house=await database.prepare(`SELECT COALESCE(SUM(oi.line_total_cents),0) revenue FROM order_items oi JOIN orders o ON o.id=oi.order_id LEFT JOIN creator_sale_snapshots s ON s.order_item_id=oi.id WHERE o.payment_status IN ('paid','refunded','disputed') AND s.id IS NULL`).first();return{balances,houseRevenueCents:Number(house?.revenue||0),reconciliation:await reconcileCreatorFinance(database)};}
export async function recordManualPayout(database,input){const creatorId=String(input.creatorId||""),currency=String(input.currency||"USD").toUpperCase(),amount=Number(input.amountCents),now=String(input.paidAt||new Date().toISOString()),key=String(input.idempotencyKey||"").trim(),actor=String(input.operatorActor||"");if(!creatorId||!Number.isInteger(amount)||amount<=0||currency.length!==3||!key||!actor)throw new Error("Payout fields are invalid.");const finance=await getCreatorFinance(database,creatorId,{nowMs:Date.parse(now)});if(finance.summary.availableBalanceCents<amount)throw new Error("Payout exceeds the eligible available balance.");const payoutId=crypto.randomUUID(),reason=String(input.reference||"").slice(0,200),note=String(input.note||"").slice(0,1000);await database.batch([database.prepare("INSERT INTO creator_payouts(id,creator_id,amount_cents,currency,reference,note,idempotency_key,operator_actor,paid_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(payoutId,creatorId,amount,currency,reason,note,key,actor,now,now),database.prepare(`INSERT INTO creator_earnings_ledger(creator_id,entry_type,amount_cents,currency,available_at,payout_state,reason,operator_actor,idempotency_key,created_at) VALUES(?,'payout',?,?,?,'paid',?,?,?,?)`).bind(creatorId,-amount,currency,now,`Payout: ${reason}`,actor,`payout:${key}`,now),database.prepare("INSERT INTO creator_financial_audit(creator_id,actor_type,actor_id,action,amount_cents,currency,context_json,created_at) VALUES(?,'operator',?,'payout_recorded',?,?,?,?)").bind(creatorId,actor,amount,currency,JSON.stringify({payoutId,reference:reason}),now)]);return{payoutId,amountCents:amount};}
export async function recordManualAdjustment(database,input){const creatorId=String(input.creatorId||''),amount=Number(input.amountCents),currency=String(input.currency||'USD').toUpperCase(),actor=String(input.operatorActor||''),reason=String(input.reason||'').trim().slice(0,1000),key=String(input.idempotencyKey||'').trim(),now=String(input.createdAt||new Date().toISOString());if(!creatorId||!Number.isInteger(amount)||!amount||currency.length!==3||!actor||!reason||!key)throw new Error('Adjustment fields are invalid.');await database.batch([database.prepare(`INSERT INTO creator_earnings_ledger(creator_id,entry_type,amount_cents,currency,available_at,payout_state,reason,operator_actor,idempotency_key,created_at) VALUES(?,'manual_adjustment',?,?,?,'available',?,?,?,?)`).bind(creatorId,amount,currency,now,reason,actor,`adjustment:${key}`,now),database.prepare("INSERT INTO creator_financial_audit(creator_id,actor_type,actor_id,action,amount_cents,currency,context_json,created_at) VALUES(?,'operator',?,'manual_adjustment',?,?,?,?)").bind(creatorId,actor,amount,currency,JSON.stringify({reason}),now)]);return{amountCents:amount};}
export async function setCreatorLedgerHold(database,input){const creatorId=String(input.creatorId||''),held=Boolean(input.held),actor=String(input.operatorActor||''),reason=String(input.reason||'').trim().slice(0,1000),now=String(input.createdAt||new Date().toISOString());if(!creatorId||!actor||!reason)throw new Error('Hold fields are invalid.');await database.batch([database.prepare("UPDATE creator_earnings_ledger SET payout_state=CASE WHEN ?=1 THEN 'held' WHEN available_at<=? THEN 'available' ELSE 'pending' END WHERE creator_id=? AND entry_type<>'payout' AND payout_state IN ('pending','available','held')").bind(held?1:0,now,creatorId),database.prepare("INSERT INTO creator_financial_audit(creator_id,actor_type,actor_id,action,context_json,created_at) VALUES(?,'operator',?,?,?,?)").bind(creatorId,actor,held?'hold_applied':'hold_released',JSON.stringify({reason}),now)]);return{held};}
export async function reconcileCreatorFinance(database){const exceptions=[];const missing=await rows(database.prepare(`SELECT oi.order_id,oi.id order_item_id,oi.product_slug FROM order_items oi JOIN orders o ON o.id=oi.order_id LEFT JOIN creator_listings cl ON cl.source_product_slug=oi.product_slug OR cl.public_product_slug=oi.product_slug LEFT JOIN creator_bundles cb ON cb.public_bundle_slug=oi.product_slug AND cb.publication_state='published' LEFT JOIN creator_sale_snapshots s ON s.order_item_id=oi.id WHERE o.payment_status IN ('paid','refunded','disputed') AND COALESCE(cl.creator_id,cb.creator_id) IS NOT NULL AND s.id IS NULL`));for(const row of missing)exceptions.push({code:"paid_line_missing_sale",...row});const missingLedger=await rows(database.prepare(`SELECT s.order_id,s.order_item_id,s.product_slug FROM creator_sale_snapshots s LEFT JOIN creator_earnings_ledger l ON l.order_item_id=s.order_item_id AND l.entry_type='sale_earning' WHERE l.id IS NULL`));for(const row of missingLedger)exceptions.push({code:"paid_line_missing_sale",...row});const missingReversal=await rows(database.prepare(`SELECT DISTINCT o.id order_id,o.payment_status FROM orders o JOIN creator_sale_snapshots s ON s.order_id=o.id LEFT JOIN creator_reversal_snapshots r ON r.order_id=o.id WHERE o.payment_status IN ('refunded','disputed') AND r.id IS NULL`));for(const row of missingReversal)exceptions.push({code:row.payment_status==='disputed'?"chargeback_missing_reversal":"refund_missing_reversal",...row});const duplicates=await rows(database.prepare("SELECT order_item_id,COUNT(*) count FROM creator_earnings_ledger WHERE entry_type='sale_earning' GROUP BY order_item_id HAVING COUNT(*)>1"));for(const row of duplicates)exceptions.push({code:"duplicate_sale_entry",...row});const negative=await rows(database.prepare("SELECT creator_id,currency,SUM(amount_cents) balance FROM creator_earnings_ledger GROUP BY creator_id,currency HAVING SUM(amount_cents)<0"));for(const row of negative)exceptions.push({code:"negative_creator_balance",...row});const orphans=await rows(database.prepare("SELECT l.id FROM creator_earnings_ledger l LEFT JOIN orders o ON o.id=l.order_id WHERE l.order_id IS NOT NULL AND o.id IS NULL"));for(const row of orphans)exceptions.push({code:"ledger_missing_order",...row});return exceptions;}
export function statementCsv(creator,period,finance){const lines=[["Creator",creator.display_name],["Period",`${period.from} through ${period.to}`],[],["Product sales"],["Date","Product","Quantity","Gross cents","Marketplace fee cents","Creator net cents","Currency"]];for(const sale of finance.sales||[])lines.push([sale.sold_at,sale.product_title,sale.quantity,sale.gross_cents,sale.marketplace_fee_cents,sale.creator_net_cents,sale.currency]);lines.push([],['Ledger activity'],["Date","Type","Product","Amount cents","Currency","Reason"]);for(const entry of finance.entries)lines.push([entry.created_at,entry.entry_type,entry.product_slug||"",entry.amount_cents,entry.currency,entry.reason]);lines.push([],['Closing unpaid balance',finance.summary.unpaidBalanceCents,'cents']);return lines.map(row=>row.map(csv).join(",")).join("\r\n")+"\r\n";}
function summarize(entries,now){const gross=entries.filter(e=>e.entry_type==='sale_earning').reduce((s,e)=>s+Number(e.amount_cents),0),reversals=entries.filter(e=>['refund_reversal','chargeback_reversal'].includes(e.entry_type)).reduce((s,e)=>s+Number(e.amount_cents),0),payouts=-entries.filter(e=>e.entry_type==='payout').reduce((s,e)=>s+Number(e.amount_cents),0),unpaid=entries.reduce((s,e)=>s+Number(e.amount_cents),0),available=entries.filter(e=>e.payout_state!=='held'&&e.available_at<=now).reduce((s,e)=>s+Number(e.amount_cents),0);return{summary:{creatorNetSalesCents:gross,refundsAndAdjustmentsCents:reversals,unpaidBalanceCents:unpaid,availableBalanceCents:Math.max(0,available),onHoldCents:Math.max(0,unpaid-available),paidBalanceCents:payouts,lifetimeEarningsCents:gross+reversals},entries};}
async function rows(statement){const result=await statement.all();return result.results||[];}function csv(value){const text=String(value??"");return /[",\r\n]/.test(text)?`"${text.replace(/"/g,'""')}"`:text;}
