// Generated from data/products.json by scripts/build-runtime-catalog.mjs.
// Do not hand-edit this file.

export const RUNTIME_PRICING_POLICY = Object.freeze({
  "includedTaxTotalCents": null,
  "pricingNote": "The listed price is the final price. Any applicable sales tax is included.",
  "taxInclusive": true
});

export const RUNTIME_CATALOG_PRODUCTS = Object.freeze([
  {
    "authorDisplay": "RV Sawyer",
    "authorSlugs": [
      "rv-sawyer"
    ],
    "authors": [
      "RV Sawyer"
    ],
    "buyMode": "cart",
    "coverUrl": "/product-assets/agency/cover.webp",
    "contentDescriptors": [],
    "creatorId": "",
    "currency": "USD",
    "effectivePriceCents": null,
    "fulfillmentEligible": true,
    "genre": "",
    "gmMode": "",
    "language": "",
    "lastUpdated": "2026-06-24",
    "listedPriceCents": 0,
    "mediaType": "digital",
    "playerCountMax": null,
    "playerCountMin": null,
    "playDuration": "",
    "playMode": "",
    "prepBurden": "",
    "priceCents": null,
    "saleActive": false,
    "saleEnabled": false,
    "saleEnd": "",
    "salePriceCents": null,
    "saleStart": "",
    "rulesComplexity": "",
    "slug": "agency",
    "status": "available-direct",
    "title": "Agency",
    "updateEligible": true,
    "version": "1.0"
  },
  {
    "authorDisplay": "RV Sawyer",
    "authorSlugs": [
      "rv-sawyer"
    ],
    "authors": [
      "RV Sawyer"
    ],
    "buyMode": "cart",
    "coverUrl": "/product-assets/circle-of-cinder/cover.webp",
    "contentDescriptors": [],
    "creatorId": "",
    "currency": "USD",
    "effectivePriceCents": 200,
    "fulfillmentEligible": true,
    "genre": "",
    "gmMode": "",
    "language": "",
    "lastUpdated": "2026-06-17",
    "listedPriceCents": 300,
    "mediaType": "",
    "playerCountMax": null,
    "playerCountMin": null,
    "playDuration": "",
    "playMode": "",
    "prepBurden": "",
    "priceCents": 300,
    "saleActive": true,
    "saleEnabled": true,
    "saleEnd": "",
    "salePriceCents": 200,
    "saleStart": "",
    "rulesComplexity": "",
    "slug": "circle-of-cinder",
    "status": "available-direct",
    "title": "Circle of Cinder",
    "updateEligible": true,
    "version": "2026 catalog preview"
  },
  {
    "authorDisplay": "RV Sawyer",
    "authorSlugs": [
      "rv-sawyer"
    ],
    "authors": [
      "RV Sawyer"
    ],
    "buyMode": "preview-only",
    "coverUrl": "/product-assets/final-flame/cover.webp",
    "contentDescriptors": [],
    "creatorId": "",
    "currency": "USD",
    "effectivePriceCents": null,
    "fulfillmentEligible": true,
    "genre": "",
    "gmMode": "",
    "language": "",
    "lastUpdated": "2026-06-17",
    "listedPriceCents": null,
    "mediaType": "",
    "playerCountMax": null,
    "playerCountMin": null,
    "playDuration": "",
    "playMode": "",
    "prepBurden": "",
    "priceCents": null,
    "saleActive": false,
    "saleEnabled": false,
    "saleEnd": "",
    "salePriceCents": null,
    "saleStart": "",
    "rulesComplexity": "",
    "slug": "final-flame",
    "status": "preview-available",
    "title": "Final Flame",
    "updateEligible": true,
    "version": "2026 catalog preview"
  },
  {
    "authorDisplay": "RV Sawyer",
    "authorSlugs": [
      "rv-sawyer"
    ],
    "authors": [
      "RV Sawyer"
    ],
    "buyMode": "cart",
    "coverUrl": "/product-assets/janni/cover.webp",
    "contentDescriptors": [],
    "creatorId": "",
    "currency": "USD",
    "effectivePriceCents": 499,
    "fulfillmentEligible": true,
    "genre": "fantasy",
    "gmMode": "",
    "language": "",
    "lastUpdated": "2026-07-11",
    "listedPriceCents": 499,
    "mediaType": "digital",
    "playerCountMax": null,
    "playerCountMin": null,
    "playDuration": "",
    "playMode": "",
    "prepBurden": "",
    "priceCents": 499,
    "saleActive": false,
    "saleEnabled": false,
    "saleEnd": "",
    "salePriceCents": 499,
    "saleStart": "",
    "rulesComplexity": "",
    "slug": "janni",
    "status": "available-direct",
    "title": "Janni",
    "updateEligible": true,
    "version": "1.0"
  },
  {
    "authorDisplay": "RV Sawyer",
    "authorSlugs": [
      "rv-sawyer"
    ],
    "authors": [
      "RV Sawyer"
    ],
    "buyMode": "preview-only",
    "coverUrl": "/product-assets/mouthy-monsters/cover.webp",
    "contentDescriptors": [],
    "creatorId": "",
    "currency": "USD",
    "effectivePriceCents": null,
    "fulfillmentEligible": true,
    "genre": "",
    "gmMode": "",
    "language": "",
    "lastUpdated": "2026-06-17",
    "listedPriceCents": null,
    "mediaType": "",
    "playerCountMax": null,
    "playerCountMin": null,
    "playDuration": "",
    "playMode": "",
    "prepBurden": "",
    "priceCents": null,
    "saleActive": false,
    "saleEnabled": false,
    "saleEnd": "",
    "salePriceCents": null,
    "saleStart": "",
    "rulesComplexity": "",
    "slug": "mouthy-monsters",
    "status": "preview-available",
    "title": "Mouthy Monsters",
    "updateEligible": true,
    "version": "2026 catalog preview"
  },
  {
    "authorDisplay": "RV Sawyer",
    "authorSlugs": [
      "rv-sawyer"
    ],
    "authors": [
      "RV Sawyer"
    ],
    "buyMode": "preview-only",
    "coverUrl": "/product-assets/path-of-the-janky/cover.webp",
    "contentDescriptors": [],
    "creatorId": "",
    "currency": "USD",
    "effectivePriceCents": null,
    "fulfillmentEligible": true,
    "genre": "",
    "gmMode": "",
    "language": "",
    "lastUpdated": "2026-06-17",
    "listedPriceCents": null,
    "mediaType": "",
    "playerCountMax": null,
    "playerCountMin": null,
    "playDuration": "",
    "playMode": "",
    "prepBurden": "",
    "priceCents": null,
    "saleActive": false,
    "saleEnabled": false,
    "saleEnd": "",
    "salePriceCents": null,
    "saleStart": "",
    "rulesComplexity": "",
    "slug": "path-of-the-janky",
    "status": "preview-available",
    "title": "Path of the Janky",
    "updateEligible": true,
    "version": "2026 catalog preview"
  },
  {
    "authorDisplay": "RV Sawyer",
    "authorSlugs": [
      "rv-sawyer"
    ],
    "authors": [
      "RV Sawyer"
    ],
    "buyMode": "cart",
    "coverUrl": "/product-assets/ringbound/cover.webp",
    "contentDescriptors": [],
    "creatorId": "",
    "currency": "USD",
    "effectivePriceCents": 500,
    "fulfillmentEligible": true,
    "genre": "fantasy",
    "gmMode": "",
    "language": "",
    "lastUpdated": "2026-07-10",
    "listedPriceCents": 500,
    "mediaType": "digital",
    "playerCountMax": null,
    "playerCountMin": null,
    "playDuration": "",
    "playMode": "",
    "prepBurden": "",
    "priceCents": 500,
    "saleActive": false,
    "saleEnabled": false,
    "saleEnd": "",
    "salePriceCents": null,
    "saleStart": "",
    "rulesComplexity": "",
    "slug": "ringbound",
    "status": "available-direct",
    "title": "Ringbound",
    "updateEligible": true,
    "version": "2026 catalog preview"
  },
  {
    "authorDisplay": "RV Sawyer",
    "authorSlugs": [
      "rv-sawyer"
    ],
    "authors": [
      "RV Sawyer"
    ],
    "buyMode": "preview-only",
    "coverUrl": "/product-assets/silence-and-the-spotlight/cover.webp",
    "contentDescriptors": [],
    "creatorId": "",
    "currency": "USD",
    "effectivePriceCents": null,
    "fulfillmentEligible": true,
    "genre": "",
    "gmMode": "",
    "language": "",
    "lastUpdated": "2026-06-20",
    "listedPriceCents": null,
    "mediaType": "",
    "playerCountMax": null,
    "playerCountMin": null,
    "playDuration": "",
    "playMode": "",
    "prepBurden": "",
    "priceCents": null,
    "saleActive": false,
    "saleEnabled": false,
    "saleEnd": "",
    "salePriceCents": null,
    "saleStart": "",
    "rulesComplexity": "",
    "slug": "silence-and-the-spotlight",
    "status": "preview-available",
    "title": "Silence and the Spotlight",
    "updateEligible": true,
    "version": "2026 catalog preview"
  },
  {
    "authorDisplay": "RV Sawyer",
    "authorSlugs": [
      "rv-sawyer"
    ],
    "authors": [
      "RV Sawyer"
    ],
    "buyMode": "preview-only",
    "coverUrl": "/assets/products/sirrocans/cover.webp",
    "contentDescriptors": [],
    "creatorId": "",
    "currency": "USD",
    "effectivePriceCents": null,
    "fulfillmentEligible": true,
    "genre": "fantasy",
    "gmMode": "",
    "language": "",
    "lastUpdated": "2026-05-27",
    "listedPriceCents": null,
    "mediaType": "digital",
    "playerCountMax": null,
    "playerCountMin": null,
    "playDuration": "",
    "playMode": "",
    "prepBurden": "",
    "priceCents": null,
    "saleActive": false,
    "saleEnabled": false,
    "saleEnd": "",
    "salePriceCents": null,
    "saleStart": "",
    "rulesComplexity": "",
    "slug": "sirrocans",
    "status": "preview-available",
    "title": "Sirrocans",
    "updateEligible": true,
    "version": "2026 release file"
  },
  {
    "authorDisplay": "RV Sawyer",
    "authorSlugs": [
      "rv-sawyer"
    ],
    "authors": [
      "RV Sawyer"
    ],
    "buyMode": "preview-only",
    "coverUrl": "/product-assets/spriggans/cover.webp",
    "contentDescriptors": [],
    "creatorId": "",
    "currency": "USD",
    "effectivePriceCents": null,
    "fulfillmentEligible": true,
    "genre": "",
    "gmMode": "",
    "language": "",
    "lastUpdated": "2026-06-04",
    "listedPriceCents": null,
    "mediaType": "",
    "playerCountMax": null,
    "playerCountMin": null,
    "playDuration": "",
    "playMode": "",
    "prepBurden": "",
    "priceCents": null,
    "saleActive": false,
    "saleEnabled": false,
    "saleEnd": "",
    "salePriceCents": null,
    "saleStart": "",
    "rulesComplexity": "",
    "slug": "spriggans",
    "status": "preview-available",
    "title": "Spriggans",
    "updateEligible": true,
    "version": "2026 release file"
  },
  {
    "authorDisplay": "RV Sawyer",
    "authorSlugs": [
      "rv-sawyer"
    ],
    "authors": [
      "RV Sawyer"
    ],
    "buyMode": "pay-what-you-want",
    "coverUrl": "/product-assets/tablecraft-primer/cover.webp",
    "contentDescriptors": [],
    "creatorId": "",
    "currency": "USD",
    "effectivePriceCents": null,
    "fulfillmentEligible": true,
    "genre": "",
    "gmMode": "",
    "language": "",
    "lastUpdated": "2026-06-17",
    "listedPriceCents": 0,
    "mediaType": "",
    "playerCountMax": null,
    "playerCountMin": null,
    "playDuration": "",
    "playMode": "",
    "prepBurden": "",
    "priceCents": null,
    "saleActive": false,
    "saleEnabled": false,
    "saleEnd": "",
    "salePriceCents": null,
    "saleStart": "",
    "rulesComplexity": "",
    "slug": "tablecraft-primer",
    "status": "pay-what-you-want",
    "title": "Tablecraft Primer",
    "updateEligible": true,
    "version": "2026 catalog preview"
  },
  {
    "authorDisplay": "RV Sawyer",
    "authorSlugs": [
      "rv-sawyer"
    ],
    "authors": [
      "RV Sawyer"
    ],
    "buyMode": "preview-only",
    "coverUrl": "/product-assets/yojimbo/cover.webp",
    "contentDescriptors": [],
    "creatorId": "",
    "currency": "USD",
    "effectivePriceCents": null,
    "fulfillmentEligible": true,
    "genre": "",
    "gmMode": "",
    "language": "",
    "lastUpdated": "2026-06-17",
    "listedPriceCents": null,
    "mediaType": "",
    "playerCountMax": null,
    "playerCountMin": null,
    "playDuration": "",
    "playMode": "",
    "prepBurden": "",
    "priceCents": null,
    "saleActive": false,
    "saleEnabled": false,
    "saleEnd": "",
    "salePriceCents": null,
    "saleStart": "",
    "rulesComplexity": "",
    "slug": "yojimbo",
    "status": "preview-available",
    "title": "Yojimbo",
    "updateEligible": true,
    "version": "2026 catalog preview"
  }
]);
